--- 
env: flex
runtime: python
runtime_config: 
  python_version: 3
readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 5
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 1500